# Schema for the configuration files of the System module.

guardian.settings:
  type: config_object
  label: 'Guardian'
  mapping:
    field_description:
      type: text
      label: 'Description of guarded fields.'
